import { Area } from "./AreaManager";

export enum EVENTS {
  TURN_PASSED = "TURN_PASSED",
  PLAYER_MOVED = "PLAYER_MOVED",
  LOG_EMITTED = "LOG_EMITTED",
  MOUSE_MOVED = "MOUSE_MOVED",
  HIT = "HIT",
  SHOT_FIRED = "SHOT_FIRED",
  TRAVELED = "TRAVELED",
  AREA_CREATED = "AREA_CREATED",
}

export type AREA_CREATED_PAYLOAD = { area: Area}