export const EVENTS = {
  TURN_PASSED: "TURN_PASSED",
  PLAYER_MOVED: "PLAYER_MOVED",
  ATTACK_HIT: "ATTACK_HIT",
  LOG_EMITTED: "LOG_EMITTED",
  MOUSE_MOVED: "MOUSE_MOVED",
  MOUSE_CLICKED: "MOUSE_CLICKED"
}