import { SpriteName } from "./sprites";

type Glyphs = Record<SpriteName, string>;

export const GLYPHS = {
  wood_wall: "#",
  knight: "@",
  snake: "S",
  corpse: "x",
  rock: "#",
  plank: "",
  empty: "",
  dirt: ".",
  grass: ",",
  man: "M",
  anomaly: "+",
  dog: "d",
  bullet: "",
  cheese: "",
  flame: "",
  hit: "",
  leather: "",
  wallBottomLeft: "",
  wallBottomRight: "",
  wallHorizontal: "",
  wallTopLeft: "",
  wallTopRight: "",
  wallVertical: "",
};

export const GLYPH_COLORS = {
  wood_wall: "BurlyWood",
  knight: "white",
  snake: "green",
  corpse: "grey",
  rock: "lightgray",
  plank: "BurlyWood",
  empty: "black",
  dirt: "Peru",
  dog: "brown",
  anomaly: "lightblue",
  grass: "lightgreen",
  bullet: "",
  cheese: "",
  flame: "",
  hit: "",
  man: "",
  leather: "",
  wallBottomLeft: "",
  wallBottomRight: "",
  wallHorizontal: "",
  wallTopLeft: "",
  wallTopRight: "",
  wallVertical: "",
};
